/*
 * Wallaby.js - v1.0.1328
 * https://wallabyjs.com
 * Copyright (c) 2014-2022 Wallaby.js - All Rights Reserved.
 *
 * This source code file is a part of Wallaby.js and is a proprietary (closed source) software.

 * IMPORTANT:
 * Wallaby.js is a tool made by software developers for software developers with passion and love for what we do.
 * Pirating the tool is not only illegal and just morally wrong,
 * it is also unfair to other fellow programmers who are using it legally,
 * and very harmful for the tool and its future.
 */
var ipc,electron=require("electron"),currentRequestId=0;if(global.window){try{Error.stackTraceLimit=80}catch(e){}ipc=electron.ipcRenderer,ipc.on("message",function(event,msg){eval(msg.code),ipc.send("message",{id:msg.id})})}else{process.setFdLimit&&process.setFdLimit(8192),process.on("uncaughtException",function(e){e&&e.message&&host&&host._send({type:"error",error:{message:e.message,stack:e.stack}})});var fs=require("fs"),_=require("lodash");ipc=electron.ipcMain;var app=electron.app,BrowserWindow=electron.BrowserWindow;"darwin"===process.platform&&app.dock.hide();var Host=function(){this._pages=Object.create(null),this._callbacks=Object.create(null)};Host.prototype={stop:function(){app.exit(0)},closePage:function(e){var t=e.pageId;this._destroyExistingPage(t)},evaluateOnPage:function(e,t){var i=e.pageId,r=this._pages[i];this._requestWithCorrelationId(r,{code:e.action},t)},openPage:function(e,t){var i=e.pageId,r=e.url,n=_.defaults(e.options||{},{width:800,height:600,show:!1,skipTaskbar:!0,webPreferences:{}});n.webPreferences.nodeIntegration=n.webPreferences.nodeIntegration||!1,n.webPreferences.preload=__filename,this._destroyExistingPage(i);var s=this._pages[i]=new BrowserWindow(n);s.loadURL(r),s.webContents.on("did-finish-load",function(){t({status:"success"})}),s.webContents.on("did-fail-load",function(){t({status:"failed"})})},capturePage:function(e,t){var i=e.pageId,r=this._pages[i];r?r.capturePage(function(i){fs.writeFile(e.file,i.toPng(),function(){t()})}):t()},_destroyExistingPage:function(e){var t=this._pages[e];t&&(t.destroy(),delete this._pages[e])},_send:function(e){process.send(e)},_requestWithCorrelationId:function(e,t,i){var r=this,n=++currentRequestId,s=r._callbacks[n]={done:i};t.id=n,e.webContents.send("message",t),s.timeout=setTimeout(function(){delete r._callbacks[n]},12e5)},_responseWithCorrelationId:function(e){var t=this._callbacks[e.id];delete this._callbacks[e.id],t&&(clearTimeout(t.timeout),t.done(e))}};var host=new Host;process.on("message",function(e){try{var t=host[e.type];t&&(e.id?t.call(host,e,function(t){t=t||{},t.id=e.id,host._send(t)}):t.call(host,e))}catch(i){host._send({type:"error",error:{message:i.message,stack:i.stack}})}}),ipc.on("message",function(e,t){t.id&&host._responseWithCorrelationId(t)}),ipc.on("resizeWindow",function(e,t){var i=host._pages[t.pageId];if(i){var r=i.getSize();i.setSize(t.width||r[0],t.height||r[1]),i.webContents.send("resizeWindow")}}),app.on("ready",function(){host._send({type:"ready"})}),app.on("before-quit",function(e){e.preventDefault()})}